# # Pre-commit (https://pre-commit.com)
# Install:
#   pip install pre-commit
#   or
#   conda install -c conda-forge pre-commit
# Add a pre-commit configuration:
#   $ pre-commit install
# (Optional) Run against all files
#   $ pre-commit run --all-files

repos:
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.8.4
    hooks:
      - id: nbqa-pyupgrade
        args: ["--py39-plus"]
      - id: nbqa-isort
      - id: nbqa-black

  - repo: https://github.com/keewis/blackdoc
    rev: v0.3.9
    hooks:
      - id: blackdoc

  - repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks:
      - id: nbstripout
        args: [ --extra-keys=metadata.kernelspec metadata.language_info.version ]
