# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Pyxel tutorials and examples
author: The Pyxel developers
logo: images/pyxel_logo.png
copyright: "2017-2022"
only_build_toc_files: true

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
#  execute_notebooks: force
#  execute_notebooks: auto
  execute_notebooks: cache
  timeout: 450

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Configure your Binder links, such as the URL of the BinderHub.
launch_buttons:
  notebook_interface: jupyterlab
  binderhub_url: 'https://mybinder.org'

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://gitlab.com/esa/pyxel-data # Online location of your book
#  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  home_page_in_navbar: false
#  use_issues_button: true
  use_repository_button: true
  use_binder_button: true
  use_edit_page_button: true
#  announcement: "My announcement!"


# Use MathJax version 3
sphinx:
  config:
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    language: en  # To improve accessibility

parse:
  myst_enable_extensions:  # default extensions to enable in the myst parser. See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    - html_image
    - amsmath
    - dollarmath    # Parsing of dollar $ and $$ encapsulated math

exclude_patterns:
  - .venv/*
  - env/*
  - .tox